version: '3.8'
services:
  rentcontrol:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - port=8000
    image: rentcontrol
    container_name: rentcontrol
    restart: unless-stopped
    volumes:
      - ./:/app
    ports: 
      - 8000:8000
    networks:
      - rentcontrol
networks:
    rentcontrol:
